# Generated by Django 3.1.1 on 2020-10-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitem',
            name='unitary_price',
        ),
        migrations.AddField(
            model_name='tableitem',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
