# Generated by Django 3.1.1 on 2020-12-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201030_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
