# Generated by Django 3.1.1 on 2020-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_ordertable_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitem',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='tableitem',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('prepearing', 'prepearing'), ('asked', 'asked')], default='asked', max_length=10),
        ),
    ]
