# Generated by Django 3.1.1 on 2020-09-29 04:56

from django.db import migrations, models
from b2_storage.storage import B2Storage


storage = B2Storage()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_auto_20200928_0253"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=1, storage=storage, upload_to="products/"),
            preserve_default=False,
        ),
    ]
