# Generated by Django 3.1.1 on 2020-10-01 21:58

from django.db import migrations, models
from b2_storage.storage import B2Storage

storage = B2Storage()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, storage=storage, upload_to="products/"
            ),
        ),
    ]
