# Generated by Django 3.1.1 on 2020-11-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20201022_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('pending', 'pending'), ('processing', 'processing'), ('delivering', 'delivering'), ('ready', 'ready')], default='pending', max_length=10),
        ),
    ]
