# Generated by Django 3.1.1 on 2020-12-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_typeproduct_only_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order_n', 'pk']},
        ),
    ]
